version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: node:12

jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .
  lint_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run lint
          command: npm run lint
      - run:
          name: Run tests
          command: npm run test

workflows:
  version: 2
  build:
    jobs:
      - checkout:
          filters:
            branches:
              only: /.*/
      - lint_test:
          filters:
            branches:
              only: /.*/
          requires:
            - checkout
